# Generated by Django 5.0.4 on 2024-04-25 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='asignacionAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAsignatura', models.CharField(max_length=100)),
                ('descripcionAsignatura', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProgramaEducativo', models.IntegerField()),
                ('cuatrimestre', models.IntegerField(blank=True, null=True)),
                ('grupoLetra', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePE', models.TextField(max_length=200)),
                ('descrpcionPe', models.TextField(max_length=200)),
                ('perfilIngreso', models.TextField(max_length=200)),
                ('perfilEgreso', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCurso', models.CharField(max_length=100)),
                ('fechainicio', models.DateField(blank=True, null=True)),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('idAsignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proyecto.asignatura')),
                ('idGrupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proyecto.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEvidencia', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('anexo', models.FileField(upload_to='archivos/')),
                ('tipoEvidencia', models.CharField(max_length=100)),
                ('idCurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proyecto.curso')),
            ],
        ),
        migrations.CreateModel(
            name='asignacionEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEntrega', models.DateField(blank=True, null=True)),
                ('idEvidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proyecto.evidencia')),
                ('idGrupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proyecto.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='evidenciaEntregada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArchivoEntregado', models.FileField(upload_to='archivos/')),
                ('calificacionEvidencia', models.DecimalField(decimal_places=2, max_digits=2)),
                ('idasignacionAlumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proyecto.asignacionalumno')),
                ('idasignacionEvidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proyecto.asignacionevidencia')),
            ],
        ),
        migrations.AddField(
            model_name='asignacionalumno',
            name='idGrupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proyecto.grupo'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='idProgramaEducativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proyecto.programaeducativo'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=50)),
                ('aPaterno', models.CharField(max_length=50)),
                ('aMaterno', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('tipoU', models.CharField(max_length=50)),
                ('correoE', models.CharField(max_length=50)),
                ('contra', models.CharField(max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asignacionalumno',
            name='idUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proyecto.usuario'),
        ),
    ]
