# Generated by Django 5.0.4 on 2024-04-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correoE',
            field=models.EmailField(max_length=50),
        ),
    ]
