# Generated by Django 5.0.4 on 2024-04-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0002_alter_usuario_correoe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='tipoCurso',
            field=models.TextField(max_length=100),
        ),
    ]
