# Generated by Django 5.0.4 on 2024-04-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0004_alter_curso_fechafin_alter_curso_fechainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fechaFin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fechainicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='tipoCurso',
            field=models.CharField(max_length=100),
        ),
    ]
